### ISSUE TITLE
Broken links on pxml-lang.github.io

### ISSUE THREAD

**Issue by celtic-coder** [pxml-lang/pxml-lang.github.io#3]
Hi Christian (@pxml-lang),

I was checking out your article [Open-Source Parser For PracticalXML (pXML)](https://pxml-lang.github.io/docs/articles/open-source-parser-for-practical-xml/index.html#ch__16), when I found that there were several broken links in it. I then checked the overall site and these are the one I found:

### [FAQ](https://pxml-lang.github.io/about/faq.html)

- Github: (https://github.com/pxml-lang/java_parser)
  Note: This is broken on the Downloads and the article pages (below).

### [Open-Source Parser For PracticalXML (pXML)](https://pxml-lang.github.io/docs/articles/open-source-parser-for-practical-xml/index.html)

- GitHub: (https://github.com/pxml-lang/java_parser)

- examples repo: (https://github.com/pxml-lang/java_examples/tree/main/src/main/java/dev/pxml/examples/validation/XMLSchemaValidatorExamples.java)

- follows: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/IParserEventsHandler.java)

- CreateDOM_ParserEventHandler: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/CreateDOM_ParserEventHandler.java)

- CreateAST_ParserEventHandler: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/CreateAST_ParserEventHandler.java)

- WriteXML_ParserEventHandler: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/WriteXML_ParserEventHandler.java)

- Logger_ParserEventHandler: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/Logger_ParserEventHandler.java)

- DoNothing_ParserEventHandler: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/DoNothing_ParserEventHandler.java)

- Timer_ParserEventHandler: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/eventHandler/Timer_ParserEventHandler.java)

- parser: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/EventStreamParser.java)

- AEventStreamParser: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/parser/AEventStreamParser.java)

- ITokenizer: (https://github.com/pxml-lang/java_parser/tree/main/src/main/java/dev/pxml/core/reader/tokenizer/ITokenizer.java)

### CSS and Favicon

- https://pxml-lang.github.io/css/pxml.css
  https://pxml-lang.github.io/images/PML_plane_200_200.png is broken.

- https://pxml-lang.github.io/docs/api/javadoc/stylesheet.css
  https://pxml-lang.github.io/docs/api/javadoc/resources/fonts/dejavu.css is broken.

- https://pxml-lang.github.io/favicon.ico
  This is broken on all pages.

Kind Regards,
Liam

**Comment by pxml-lang** [comment]
Thank you, Liam.

Most links were temporary broken because I kept some repositories private.
Since today everything is public (the pXML parser is ready), and the links to Github repos are ok.

There were two wrong links, though:
PML_plane_200_200.png
favicon.ico

I've fixed it and rechecked the site with an online tool.
Everything should be ok now.

**Comment by celtic-coder** [comment]
Great to see this work making progress! 🙂

**Comment by celtic-coder** [comment]
Hi Christian (@pxml-lang),

The only link that still appears to be broken (https://pxml-lang.github.io/docs/api/javadoc/resources/fonts/dejavu.css) is in the `@import url('resources/fonts/dejavu.css');` statement of the [Javadoc stylesheet](https://pxml-lang.github.io/docs/api/javadoc/stylesheet.css).

Have you considered adding a sitemap to the website? This would give the site visitor a good idea of the extent of the Java documentation, for example.

By the way, the link https://pxml-lang.github.io/docs/api/javadoc/serialized-form.html seems to be laid out differently to the other pages in the documentation. Is this expected?

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
By the way, the pxml-lang.dev domain is [available](https://www.namecheap.com/domains/registration/results/?domain=pxml-lang.dev), if you might be interested in keeping the domain consistent with ppl-lang.dev, pml-lang.dev, etc.

**Comment by pxml-lang** [comment]
> Great to see this work making progress!

Thank you, Liam.

> The only link that still appears to be broken ...

The whole Java API doc. is created with the standard `javadoc` tool. So this might be a minor bug in the tool. Nothing to worry about, I think. Will probably be fixed in a future version of Java.

> Have you considered adding a sitemap to the website? This would give the site visitor a good idea of the extent of the Java documentation, for example.

If you need a tree view of the Java doc. you can click on `TREE` in the menu displayed at the top of the page. The display is not very nice, but it's the standard view in Java. The whole website is currently quite small, but a sitemap should definitely be added if the site grows in the future.

> laid out differently

That's also due to the way Java does it.

> the pxml-lang.dev domain is available

Thank you. Yes, I checked that too. I intend to move to that url if there is enough interest for pXML.
